# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='statistics_str',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
